### ISSUE TITLE
Preload Failed, API version mismatch

### ISSUE THREAD

**Issue by Toskan4134** [teeebor/flipper_solitaire#3]
When you try to run the game on flipper zero, you get the error "Preload Failed, API version mismatch".
![Screenshot-20230624-203550](https://github.com/teeebor/flipper_solitaire/assets/62228706/a87ad685-c7a9-4f6c-b6e0-b8f26a998a19)

**Comment by teeebor** [comment]
Can you please provide more information? 
Did you build it yourself, or downloaded the fap file? If the latter please tell where you get it. 
What firmware and which version are you using?

**Comment by Toskan4134** [comment]
I built it by myself and I'm using the 0.85.2 Firmware, tell me if you need more info

**Comment by teeebor** [comment]
Try with the fap file from the releases page. 

My best guess is that you just cloned the firmware repository, but didn't change it to the version you are on.
To do this:
* Open a terminal window in your firmware's folder
* type in: ``` git checkout 0.85.2 ``` after that you should be able to build it yourself

**Comment by Toskan4134** [comment]
Yup, it's working, tysm
